# Generated by Django 4.1 on 2023-04-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registroSafely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('area', models.CharField(max_length=50, verbose_name='Área de Trabajo')),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='registroSafelyEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('rubro', models.CharField(max_length=50, verbose_name='Rubro')),
            ],
        ),
    ]
